# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'keyclue' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'NVActivityIndicatorView'
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/DynamicLinks’
end
